/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio.i.datos.ii;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.tree.DefaultTreeSelectionModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
/**
 *
 * @author ofortich
 */
public class GestorFrame extends javax.swing.JFrame {
    Nodo ptr = new Nodo("ptr",true);
    File file = new File("file.txt");
    File usuario = new File("usuario.txt");
    FileWriter w;
    BufferedWriter bw;
    PrintWriter pw;
    
    Usuario usuarioUnico = new Usuario();
    DefaultTreeModel modelo = new DefaultTreeModel(ptr);
    /**
     * Creates new form GestorFrame
     */
    public GestorFrame() throws IOException {
        initComponents();
        leerUsuario(usuario,usuarioUnico);
        leerArchivo(file,ptr,modelo,jTree);
        
        // Construccion de los datos del arbol ejemplo
        /*
        DefaultMutableTreeNode padre = new DefaultMutableTreeNode("padre");
        modelo.insertNodeInto(padre, ptr, 0);
        
        DefaultMutableTreeNode tio = new DefaultMutableTreeNode("tio");
        
        modelo.insertNodeInto(tio, ptr, 0);
            
        DefaultMutableTreeNode hijo = new DefaultMutableTreeNode("hijo");
        DefaultMutableTreeNode hija = new DefaultMutableTreeNode("hija");
        
        modelo.insertNodeInto(hijo, tio, 0);
        modelo.insertNodeInto(hija, padre, 0);
        */
        jTree.setModel(modelo);   
        jTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        nombrePaquetetxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        añadir = new javax.swing.JButton();
        txtEntregable = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        dibujarbtn = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        modelo1 = new DefaultListModel();
        preList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        modelo2 = new DefaultListModel();
        inList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        modelo3 = new DefaultListModel();
        postList = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jFrame3 = new javax.swing.JFrame();
        drawPanel = new java.awt.Panel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        nombreAccounttxt = new javax.swing.JTextField();
        contraseñaAccounttxt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(560, 500));

        jLabel1.setText("Nombre del Paquete");

        jButton1.setText("Agregar Paquete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTree.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jTree.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTreeFocusGained(evt);
            }
        });
        jTree.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
                jTreeTreeCollapsed(evt);
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                jTreeTreeExpanded(evt);
            }
        });
        jTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMouseClicked(evt);
            }
        });
        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        añadir.setText("Añadir Entregable");
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });

        txtEntregable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntregableActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Entregable");

        jButton2.setText("Generar Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Guardar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Descripción");

        jLabel9.setText("Fecha del entregable");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(labelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dibujarbtn.setText("Dibujar");
        dibujarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibujarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)))
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombrePaquetetxt)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jButton2))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEntregable)
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(añadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dibujarbtn)
                        .addContainerGap())))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(nombrePaquetetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEntregable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(dibujarbtn)))
                .addGap(63, 63, 63)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(añadir)
                    .addComponent(jButton6))
                .addGap(25, 25, 25))
        );

        jFrame2.setMinimumSize(new java.awt.Dimension(400, 350));

        jLabel5.setText("Recorrido PreOrden");

        jLabel6.setText("Recorrido InOrden");

        jLabel7.setText("Recorrido PostOrden");

        preList.setModel(modelo1);
        jScrollPane2.setViewportView(preList);

        inList.setModel(modelo2);
        jScrollPane3.setViewportView(inList);

        postList.setModel(modelo3);
        jScrollPane4.setViewportView(postList);

        jButton3.setText("Recorrer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButton3)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Cronograma");

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setText("Iniciar sesion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Crear cuenta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre de usuario");

        jLabel4.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contraseñaAccounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(nombreAccounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAccounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseñaAccounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(nombreAccounttxt.getText().equals(usuarioUnico.getName()) && contraseñaAccounttxt.getText().equals(usuarioUnico.getPassword())){
            jFrame1.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error, usuario invalido");
            nombreAccounttxt.setText("");
            contraseñaAccounttxt.setText("");
        }        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Nodo p=ptr;
            
        if (!(ptr.existe(nombrePaquetetxt.getText(), p)) && !(nombrePaquetetxt.getText().equals(""))) {
            System.out.println("agrega "+nombrePaquetetxt.getText());
            ptr.add(nombrePaquetetxt.getText(),true);
            DefaultMutableTreeNode padre = new DefaultMutableTreeNode(nombrePaquetetxt.getText());
            modelo.insertNodeInto(padre, ptr, ptr.getChildCount());
            nombrePaquetetxt.setText("");
        }else{
            if(nombrePaquetetxt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Nombre de paquete invalido");
                nombrePaquetetxt.setText("");
            }
            if(ptr.existe(nombrePaquetetxt.getText(), p)){
                JOptionPane.showMessageDialog(null, "Ese paquete ya existe");
                nombrePaquetetxt.setText("");
            }
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (nombreAccounttxt.getText().equals("") && contraseñaAccounttxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "parametros incorrectos");

        } else {
            usuarioUnico.setName(nombreAccounttxt.getText());
            usuarioUnico.setPassword(contraseñaAccounttxt.getText());
            nombreAccounttxt.setText("");
            contraseñaAccounttxt.setText("");
            FileWriter f;
            try {
                f = new FileWriter(usuario);
                BufferedWriter b = new BufferedWriter(f);
                b.write(usuarioUnico.getName());
                b.newLine();
                b.write(usuarioUnico.getPassword());
                b.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GestorFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GestorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(null, "Cuenta creada con exito");
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
        añadir.enable(true);
    }//GEN-LAST:event_jTreeValueChanged

    private void jTreeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTreeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTreeFocusGained

    private void jTreeTreeExpanded(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_jTreeTreeExpanded
        // TODO add your handling code here:
        añadir.setEnabled(true);
    }//GEN-LAST:event_jTreeTreeExpanded

    private void jTreeTreeCollapsed(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_jTreeTreeCollapsed
        // TODO add your handling code here:
        añadir.setEnabled(false);
    }//GEN-LAST:event_jTreeTreeCollapsed

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
        // TODO add your handling code here:
        String nombreEntregable=txtEntregable.getText();
        //String nombrePaquete=jTree.get;
        //Nodo padre=ptr.buscarPaquete(nombrePaquete, ptr);
        Nodo p=ptr;
        Date fecha = dateChooser.getDate();
        if (!((ptr.existe(nombreEntregable, p)) || txtEntregable.getText().equals(""))&&(jTree.getLastSelectedPathComponent()!=null)) {
            System.out.println("agrega "+nombreEntregable);
            String e=jTree.getLastSelectedPathComponent().toString();
            DefaultMutableTreeNode n = (DefaultMutableTreeNode)jTree.getLastSelectedPathComponent();
            ptr.buscarPaquete(e, ptr).add(new Nodo(nombreEntregable,false,fecha));
            DefaultMutableTreeNode hijo = new DefaultMutableTreeNode(nombreEntregable);
            modelo.insertNodeInto(hijo, n, n.getChildCount());
            jTree.setModel(modelo);
            txtEntregable.setText("");
        }else{
            if(txtEntregable.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Nombre de entregable invalido");
                txtEntregable.setText("");
            }
            if(ptr.existe(txtEntregable.getText(), p)){
                JOptionPane.showMessageDialog(null, "Ese entregable ya existe");
                txtEntregable.setText("");
            }
            if (jTree.getLastSelectedPathComponent()==null) {
                JOptionPane.showMessageDialog(null, "Seleccione un Paquete");
                txtEntregable.setText("");
            }
        }
        
    }//GEN-LAST:event_añadirActionPerformed

    private void txtEntregableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntregableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntregableActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "los nodos terminales son: "+ ptr.nodosHoja(ptr));
        if (ptr.unSoloEntregable(ptr).equals("")) {
            JOptionPane.showMessageDialog(null, "No hay nodos con un solo entregable");
        }else{
            JOptionPane.showMessageDialog(null, "Los paquetes con un solo entrgable son: "+ ptr.unSoloEntregable(ptr));
        }
        JOptionPane.showMessageDialog(null, "La altura del arbol es: "+ ptr.altura(ptr));
       //frame para mostrar los recorridos
         jFrame2.setVisible(true); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        recorridoPreorden();
        recorridoInorden();
        recorridoPosorden();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        try
        {
            w = new FileWriter(file);
            bw = new BufferedWriter(w);
            pw = new PrintWriter(bw);

            Nodo p = ptr.getlLink();
            Nodo h = null;
                if (p!=null) {
                    while (p != null) {
                        h = p;
                        pw.println(p.getNombre());
                        p = p.getlLink();
                        while (h.getrLink() != null) {
                            h = h.getrLink();
                            pw.println("   "+h.getNombre());
                        }                       
                    }
                }
                
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           // Nuevamente aprovechamos el finally para 
           // asegurarnos que se cierra el fichero.
           if (null != file)
              pw.close();
              bw.close();
              JOptionPane.showMessageDialog(rootPane, "Se ha guardado correctamente");
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeMouseClicked
        // TODO add your handling code here:
        if (jTree.getLastSelectedPathComponent()!=null) {
            

            DefaultMutableTreeNode n = (DefaultMutableTreeNode)jTree.getLastSelectedPathComponent();
            String s = n.toString();
            Nodo a = ptr.buscarPaquete(n.getParent().toString(), ptr);
            if (ptr.buscarEntregable(s, a)!=null) {


                Nodo p = ptr.buscarEntregable(s, a);
                labelNombre.setText(p.getNombre());
                labelFecha.setText(p.fecha.toString());
            }
        }
        /*if (ptr.buscarPaquete(jTree.getSelectionPath().toString(),ptr)==null) {
            
        
            String s = jTree.getSelectionPath().toString();
            String pattern = "yyyy-M-dd";
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat(pattern);
            Date fecha = null;
            try {
                fecha = formatoDelTexto.parse(ptr.buscarEntregable(s, ptr).fecha.toString());
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            JTextField fechaNacimiento = new JTextField(fecha.toLocaleString());

            // Se agrega en un JTextField fechaNacimiento al panel.
            panel1.add(fechaNacimiento);
        }
        */
    }//GEN-LAST:event_jTreeMouseClicked

    private void dibujarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibujarbtnActionPerformed
        
    }//GEN-LAST:event_dibujarbtnActionPerformed
    
    public void valueChanged(TreeSelectionEvent e) {

        // Obtenemos y escribimos en pantalla  el path seleccionado
        TreePath path = e.getPath();
        Object [] nodos = path.getPath();
        System.out.print("Path seleccionado: ");
        for (Object nodo: nodos){
                System.out.print (nodo.toString() + " | ");
        System.out.println("");
        }
        // Mirando el ultimo nodo del path, sabemos qué nodo en concreto
        // se ha seleccionado.
        DefaultMutableTreeNode ultimoNodo = 
                (DefaultMutableTreeNode)nodos[nodos.length-1];

        // Por ejemplo, para ver si se ha seleccionado el "hijo1"...
        if (ultimoNodo.getUserObject().equals("hijo1"))
        {
            // Necesitamos el modeloSeleccion para saber si "hijo1" se ha
            // seleccionado o deseleccionado.
            DefaultTreeSelectionModel modeloSeleccion = 
                    (DefaultTreeSelectionModel)e.getSource();
            if (modeloSeleccion.isPathSelected(path))
                System.out.println("Has seleccionado hijo 1");
            else
                System.out.println("Has deseleccionado hijo 1");
        }
    }
    public void recorridoPreorden()
    {
        ayudantePreorden(ptr);
    }
    
    //recorrido preorden 
    private void ayudantePreorden(Nodo nodo) {
        if (nodo == null) {
            return;
        }

        System.out.print(nodo.getNombre() + " ");
        modelo1.addElement(nodo.getNombre());
        ayudantePreorden(nodo.getlLink());   
        ayudantePreorden(nodo.getrLink());     
    }
    
    public void recorridoInorden()
    {
        ayudanteInorden(ptr);
    }
     //recorrido inorden
    private void ayudanteInorden( Nodo nodo)
    {
        if(nodo == null)
            return;
         
        ayudanteInorden(nodo.getlLink());
        System.out.print(nodo.getNombre() + " ");
        modelo2.addElement(nodo.getNombre());
        ayudanteInorden(nodo.getrLink());
    }
    
    public void recorridoPosorden()
    {
        ayudantePosorden(ptr);        
    }
     
    //recorrido posorden
    private void ayudantePosorden(Nodo nodo)
    {
        if( nodo == null )
            return;
         
        ayudantePosorden(nodo.getlLink());
        ayudantePosorden(nodo.getrLink());
        System.out.print(nodo.getNombre() + " ");
        modelo3.addElement(nodo.getNombre());
    }
    void leerUsuario(File archivo, Usuario usuario) throws FileNotFoundException, IOException{
        
        FileReader f = new FileReader(archivo);
        BufferedReader b = new BufferedReader(f);
        usuario.setName(b.readLine());
        usuario.setPassword(b.readLine());
        b.close();
    }
    void leerArchivo(File archivo, Nodo ptr, DefaultTreeModel modelo, javax.swing.JTree jTree) throws FileNotFoundException, IOException {
        String a;
        Nodo p=ptr;
        FileReader f = new FileReader(archivo);
        String padr="";
        DefaultMutableTreeNode padre=null;
        try (BufferedReader b = new BufferedReader(f)) {
            while((a = b.readLine())!=null) {
                if (!(a.contains("   "))) {
                    if (!(ptr.existe(a, p)) && !(a.equals(""))) {
                        System.out.println("agrega "+a);
                        ptr.add(a,true);
                        padre = new DefaultMutableTreeNode(a.trim());
                        modelo.insertNodeInto(padre, ptr, ptr.getChildCount());
                    }else{
                        if(a.equals("")){
                        }
                        if(ptr.existe(a, p)){
                        }
                    }
                    padr = a;
                }
                
                if(a.startsWith("   ")){
                        String nombreEntregable=a.trim();
                        //String nombrePaquete=jTree.get;
                        //Nodo padre=ptr.buscarPaquete(nombrePaquete, ptr);
                        if (!(ptr.existe(nombreEntregable, p))) {
                            System.out.println("agrega "+nombreEntregable);
                            ptr.buscarPaquete(padr, ptr).add(nombreEntregable,false);
                            DefaultMutableTreeNode n = new DefaultMutableTreeNode(nombreEntregable);
                            DefaultMutableTreeNode hijo = new DefaultMutableTreeNode(nombreEntregable);
                            modelo.insertNodeInto(hijo, padre, padre.getChildCount());
                        }else{
                            if(a.equals("")){
                                JOptionPane.showMessageDialog(null, "Nombre de entregable invalido");
                            }
                            if(ptr.existe(a, p)){
                                JOptionPane.showMessageDialog(null, "Ese entregable ya existe");
                            }
                            if (jTree.getLastSelectedPathComponent()==null) {
                                JOptionPane.showMessageDialog(null, "Seleccione un Paquete");
                            }
                        }
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GestorFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GestorFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadir;
    private javax.swing.JPasswordField contraseñaAccounttxt;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton dibujarbtn;
    private java.awt.Panel drawPanel;
    private javax.swing.JList<String> inList;
    public DefaultListModel modelo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTree jTree;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField nombreAccounttxt;
    private javax.swing.JTextField nombrePaquetetxt;
    private javax.swing.JPanel panel1;
    private javax.swing.JList<String> postList;
    public DefaultListModel modelo3;
    private javax.swing.JList<String> preList;
    public DefaultListModel modelo1;
    private javax.swing.JTextField txtEntregable;
    // End of variables declaration//GEN-END:variables
}
